name: "High Performance Core Data"
keywords:
- Matthew Morey
- Core Data
markdown: redcarpet
redcarpet:
  extensions: []
permalink: /:title
highlighter: pygments
exclude: [README.md, TODO.md, Gemfile*]
safe: true
